spring:
  application:
    name: api
  config:
    import: optional:secrets-config.properties
  jpa:
    show-sql: true
    # hibernate:
    #   ddl-auto: update
    # properties:
    #   hibernate:
    #     format_sql: true
    #     dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url:  jdbc:mariadb://${DATABASE_HOST}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    # driver-class-name: com.mysql.cj.jdbc.Driver
server:
  error:
    include-stacktrace: never
api:
  security:
    token:
      secret: ${API_SECRET}
      issuer: ${TOKEN_ISSUER}
